### ISSUE TITLE
adaptive stream 2.4.3 couldn't be satisifed

### ISSUE THREAD

**Issue by evilsuperstar29** [add-ons/plugin.video.vtm.go#155]
I get the following error adaptive stream 2.4.3. couldn't be satisfied, although I have the most recent version of adaptive stream.

**Comment by michaelarnauts** [comment]
Please don't remove the bug template, I can't help you now.

**Comment by davidbe** [comment]
I have the same problem. Now with template:

**Describe the bug**
When trying to install version 1.0.0 of VTM GO addon on Kodi via the official Kodi repo, I cannot install it and I get error message: "adaptive stream 2.4.3. couldn't be satisfied".

This wasn't the case when I installed version 0.9.? from the repo that was adviced before the 1.0.0.

**To Reproduce**
Steps to reproduce the behavior:
1. Addons -> from repo
2. Choose repo Kodi (not previous location)
3. Hit Install / OK when list of proposed dependencies are shown (all of them are installed already, including adaptive stream)

**Expected behavior**
Add-on gets installed.

**System**
 - Addon version: 1.0.0
 - Kodi version: 18.5
 - Inputstream adaptive version: 2.4.3
 - Operating System: (Windows / Mac OS / Android / LibreElec / OSMC / ...) LibreElec
 - Special Hardware: (RPI / Vero4K+ / ...): Odroid C2

**Comment by evilsuperstar29** [comment]
> Please don't remove the bug template, I can't help you now.

aplogies new to this ;)

**Comment by michaelarnauts** [comment]
Are you sure you have an updated Inputstream Adaptive 2.4.3? With most distributions, this is bundled with Kodi 18.6.

**Comment by evilsuperstar29** [comment]
I'll check tonight again and take a screenshot :) 
Thanks for looking into the issue ;)

**Comment by michaelarnauts** [comment]
@evilsuperstar29 I assume your issue is fixed?

**Comment by robinmedland** [comment]
Hi guys, i am also getting this error:

the dependency on inputstream.adaptive version 2.4.3 couldn't be satisifed

I am new to kodi but for me it seams that version 2.4.3 is installed correctly.

**Comment by robinmedland** [comment]
just noticed that my inputstream version is 2.4.2, let me try to update this , just pressing update does not work

**Comment by dagwieers** [comment]
@robinmedland Inputstream Adaptive ships with your distribution of Kodi. So you will have to update your Kodi distribution (or Kodi itself if you installed it separately).

**Comment by robinmedland** [comment]
i just installed kodi today, i am running kodi 18.6 git:20200310-c668f73c38.
I am running it on my raspberry pi, any idea on how to do the update?

**Comment by dagwieers** [comment]
How did you install Kodi? LibreELEC, OpenELEC, Raspbian, ... ? (This is what we call the distribution)

**Comment by robinmedland** [comment]
pi@raspberrypi:~ $ history
    1  ls
    2  reboot
    3  sudo raspi config
    4  sudo raspi-config
    5  reboot
    6  sudo reboot
    7  sudo apt-get
    8  sudo apt-get update
    9  sudo apt-get install kodi
   10  sudo reboot
   11  sudo apt-get install kodi
   12  sudo dpkg --configure -a
   13  sudo apt-get install kodi
   14  apt --fix-broken install
   15  sudo apt --fix-broken install
   16  sudo apt-get install kodi
   17  reboot
   18  sudo apt install kodi kodi-peripheral-joystick kodi-pvr-iptvsimple kodi-inputstream-adaptive kodi-inputstream-rtmp
   19  reboot
   20  wget https://github.com/add-ons/plugin.video.viervijfzes/archive/master.zip
   21  ls
   22  rm -rf plugin.video.viervijfzes/
   23  ls
   24  rm repository.castagnait-1.0.1.zip
   25  wget https://raw.githubusercontent.com/elchocolate/repotvchopo/master/Repositorio/inputstream.adaptive/inputstream.adaptive-3.zip
   26  ls
   27  unzip inputstream.adaptive-3.zip
   28  ls
   29  cd inputstream.adaptive/
   30  ls
   31  history

**Comment by mediaminister** [comment]
Try
```
sudo apt-get install kodi-inputstream-adaptive
```

**Comment by robinmedland** [comment]
pi@raspberrypi:~ $ sudo apt-get install kodi-inputstream-adaptive
Reading package lists... Done
Building dependency tree
Reading state information... Done
kodi-inputstream-adaptive is already the newest version (2.4.2-1~buster).
0 upgraded, 0 newly installed, 0 to remove and 142 not upgraded.

I appreciate the help guys :)

**Comment by dagwieers** [comment]
Your system must have issues getting newer updates because Debian Buster ships with IA v2.4.4:
https://www.deb-multimedia.org/dists/stable/main/binary-armhf/package/kodi-inputstream-adaptive

Maybe you could consider using LibreELEC, which provides a much easier experience for running Kodi.

**Comment by robinmedland** [comment]
For all those having the same problem, i needed to uncommented a line in /etc/apt/sources.list
Afther that I did a new apt-get update and it is working right now.

Thanks for all the help, and for the great addon

**Comment by robinmedland** [comment]
Ok no fuck I was mistaken, i am still on version 2.4.2
