### ISSUE TITLE
Video of an episode restarts a couple of seconds after advertisements finished playing

### ISSUE THREAD

**Issue by kevwilde** [add-ons/plugin.video.vtm.go#170]
**Describe the bug**
When selecting an episode from VTM Go, I see an advertisement (30s), a "vtm go" splash video (5s-ish) then hear a couple of seconds (15-ish) of audio from the video and the timer resets to 0:00 again, which triggers an advertisement and the splash video again. This continues until I stop the playback.

**To Reproduce**
1. Install via repository on a libreelec on rpi4
2. Sign into VTMGo account
3. Select an episode
4. View commercial
5. View VTM Go splash screen
6. Actual episode fails playing

**Expected behavior**
After the advertisement and splash screen, the video should play.

**System**
 - Addon version: 1.0.1
 - Kodi version: Kodi 18.6
 - Inputstream adaptive version: 2.4.4.1
 - Inputstream Helper version: 0.4.5
 - Widevine version: 4.10.1610.6
 - Chrome OS version: 12739.111.1
 - Operating System: LibreElec 9.2.1 RPi4.arm 
 - Special Hardware: RPi 4

**Additional context**

**Comment by kevwilde** [comment]
Today I retried the VTM Go addon and it worked, with the following caveat. It did not show an advertisement at the beginning of the video, but only the VTM Go splash screen.

So it might be an issue related to video being interrupted by an advertisement video.

Yours to decide how to proceed with this bug ticket.

**Comment by michaelarnauts** [comment]
This is probably the same issue as #139 

Some programs don't have an advertisement at the beginning, but only the VTM GO intro video, so this is normal.

A few modifications to the video player of Kodi have been proposed that will fix these issues, but they are not approved yet. It's also not clear if or when they end up in a Kodi Leia release.
