### ISSUE TITLE
De afhankelijkheid op inputstream.adaptive versie 2.4.3 kan niet worden voldaan

### ISSUE THREAD

**Issue by Rvhalewyn** [add-ons/plugin.video.vtm.go#180]
Dit krijg ik als ik de add-on wil downloaden.

**Comment by dagwieers** [comment]
Je moet je Kodi, of je Kodi distributie (LibreELEC, OpenELEC, OSMC) bijwerken. Als vuistregel geldt hier dat je best Kodi v18.6 draait voor de VTM GO add-on.

**Comment by Rvhalewyn** [comment]
Dank voor het snelle antwoord.
Dan is het dus wachten tot deze versie beschikbaar is voor de Eminent? 

Met vriendelijke groeten
Rudy Vanhalewyn
Contactpersoon voor België van
Stichting Projecthulp Suriname
Winston Churchilllaan 23 bus 14
B-8300 Knokke-Heist

tel. +32 50 94 61 28 of +32 496 84 72 74
tel. vanuit Suriname 750 37 47
tel. vanuit Nederland +31 6 377 22 746
Viber +316 377 22 746
WhatsApp +316 377 22 746
sip:rvhalewyn@pbxes.org 
LinkedIn Rudy Vanhalewyn


-------- Origineel bericht --------
Van: Dag Wieers <notifications@github.com>
Verzonden: 21 mei 2020 02:28:36 CEST
Aan: "add-ons/plugin.video.vtm.go" <plugin.video.vtm.go@noreply.github.com>
CC: Rvhalewyn <Rudy.Vanhalewyn@gmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [add-ons/plugin.video.vtm.go] De afhankelijkheid op inputstream.adaptive versie 2.4.3 kan niet worden voldaan (#180)

Je moet je Kodi, of je Kodi distributie (LibreELEC, OpenELEC, OSMC) bijwerken. Als vuistregel geldt hier dat je best Kodi v18.6 draait voor de VTM GO add-on.

**Comment by dagwieers** [comment]
In dat geval zal u moeten te rade gaan bij je leverancier.

**Comment by TheGroundZero** [comment]
Ik krijg deze error ook.

Ik heb een OSMC Vero 4K+, die draait OSMC 2019.07-1 (kernel 3.14.29-152-osmc) met Kodi 18.3.

VRT NU app kon ik wel installeren.  
Dependencie-lijst toont ook dat inputstream.adaptive versie 2.4.3 geïnstalleerd is.

**Comment by michaelarnauts** [comment]
> Ik krijg deze error ook.
> 
> Ik heb een OSMC Vero 4K+, die draait OSMC 2019.07-1 (kernel 3.14.29-152-osmc) met Kodi 18.3.
> 
> VRT NU app kon ik wel installeren.
> Dependencie-lijst toont ook dat inputstream.adaptive versie 2.4.3 geïnstalleerd is.

Ik heb ook een Vero4K+, maar jij draait wel een heel oude versie. Je moet eens kijken waarom die niet update... De laatste stable OSMC draait Kodi 18.6.

**Comment by TheGroundZero** [comment]
> 
> 
> > Ik krijg deze error ook.
> > Ik heb een OSMC Vero 4K+, die draait OSMC 2019.07-1 (kernel 3.14.29-152-osmc) met Kodi 18.3.
> > VRT NU app kon ik wel installeren.
> > Dependencie-lijst toont ook dat inputstream.adaptive versie 2.4.3 geïnstalleerd is.
> 
> Ik heb ook een Vero4K+, maar jij draait wel een heel oude versie. Je moet eens kijken waarom die niet update... De laatste stable OSMC draait Kodi 18.6.

NFS issue op m'n NAS waardoor er geen backup werd gemaakt.  
Ik veronderstel dat dit de upgrade tengenhield. 🤦‍♂️  
Nu draai ik OSMC 2020.03-1 (Kodi 18.6).

Fixed

**Comment by Rvhalewyn** [comment]
Ik heb een Eminent em7680 op Kodi 18.4. 

De ontwikkelaars blijken niet bereid om naar Kodi 18.6 te gaan, omdat ze die versie irrelevant vinden voor de werking. Add-ons interesseren hun niet.

Is er geen andere oplossing voor de vtm add-on? 

Met vriendelijke groeten
Rudy Vanhalewyn
Contactpersoon voor België van
Stichting Projecthulp Suriname
Winston Churchilllaan 23 bus 14
B-8300 Knokke-Heist

tel. +32 50 94 61 28 of +32 496 84 72 74
tel. vanuit Suriname 750 37 47
tel. vanuit Nederland +31 6 377 22 746
Viber +316 377 22 746
WhatsApp +316 377 22 746
sip:rvhalewyn@pbxes.org 
LinkedIn Rudy Vanhalewyn


-------- Origineel bericht --------
Van: TheGroundZero <notifications@github.com>
Verzonden: 28 mei 2020 23:13:36 CEST
Aan: "add-ons/plugin.video.vtm.go" <plugin.video.vtm.go@noreply.github.com>
CC: Rvhalewyn <Rudy.Vanhalewyn@gmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [add-ons/plugin.video.vtm.go] De afhankelijkheid op inputstream.adaptive versie 2.4.3 kan niet worden voldaan (#180)

> 
> 
> > Ik krijg deze error ook.
> > Ik heb een OSMC Vero 4K+, die draait OSMC 2019.07-1 (kernel 3.14.29-152-osmc) met Kodi 18.3.
> > VRT NU app kon ik wel installeren.
> > Dependencie-lijst toont ook dat inputstream.adaptive versie 2.4.3 geïnstalleerd is.
> 
> Ik heb ook een Vero4K+, maar jij draait wel een heel oude versie. Je moet eens kijken waarom die niet update... De laatste stable OSMC draait Kodi 18.6.

NFS issue op m'n NAS waardoor er geen backup werd gemaakt.  
Ik veronderstel dat dit de upgrade tengenhield. 🤦‍♂️  
Nu draai ik OSMC 2020.03-1 (Kodi 18.6).

Fixed

**Comment by dagwieers** [comment]
> Is er geen andere oplossing voor de vtm add-on?

Nee, sorry, je hebt een nieuwe InputStream Adaptive add-on nodig, en die moet gecompileerd zijn tegen de Kodi versie die jij hebt. In dit geval zijn de ontwikkelaars hiervoor het aanspreekpunt.

Intussen is Kodi v18.7 gereleased, misschien vinden ze deze versie wel relevant. Of misschien ook niet.

**Comment by michaelarnauts** [comment]
> Is er geen andere oplossing voor de vtm add-on?

Ik zou eens kijken naar een andere manier om Kodi te kijken. Zelf heb ik een Vero4K+ (https://osmc.tv/vero/) staan thuis, en ben er heel tevreden van. Wordt heel goed ondersteund, en de ontwikkelaar erachter (Sam) doet echt goed z'n best!
