### ISSUE TITLE
addon werkt niet meer in Kodi19

### ISSUE THREAD

**Issue by kengithub9** [add-ons/plugin.video.vtm.go#189]
**Describe the bug**

**To Reproduce**
1.
2.
3.

**Expected behavior**

**Screenshots**

**System**
 - Addon version: 1.02
 - Kodi version: 19
 - Inputstream adaptive version:
 - Operating System: (Windows / Mac OS / Android / LibreElec / OSMC / ...)
 - Special Hardware: (RPI / Vero4K+ / ...)

**Additional context**
De addon werkt helaas niet meer met de recentste versie van Kodi19.

**Comment by michaelarnauts** [comment]
Zou je kunnen aangeven wat niet meer werkt, en welke error je in je log krijgt?

**Comment by kengithub9** [comment]
De hele addon is gedeactiveerd door Kodi19 build van 28 juni 2020. Ik kan hem dus helemaal niet meer openen. De error die zeer kort onder in beeld kwam had het over phyton 2 nog wat.

**Comment by michaelarnauts** [comment]
Ahja, klopt. Kodi heeft Addons bewust incompatible gemaakt voor Matrix, ondanks dat de code wel werkt. Je moet in de addon.xml de versie van xbmc.python op 3.0.0 zetten, dan zou die wel moeten werken.

**Comment by kengithub9** [comment]
Hoe en waar moet ik dat aanpassen?

**Comment by michaelarnauts** [comment]
In het mapje waar je de addon hebt staan, moet je de file `addon.xml` aanpassen, daar moet je 
```
<import addon="xbmc.python" version="2.26.0"/>
```
veranderen in 
```
<import addon="xbmc.python" version="3.0.0"/>
```
