### ISSUE TITLE
LOGNOTICE is deprecated in Matrix, we should use LOGINFO on Kodi Matrix

### ISSUE THREAD

**Issue by michaelarnauts** [add-ons/plugin.video.vtm.go#193]
**Describe the bug**
LOGNOTICE is deprecated in Matrix, we should use LOGINFO.

In Kodi 18, LOGNOTICE will be logged to the log without Kodi debugging enabled, therefore, we increase logging from DEBUG to LOGNOTICE when we have `debug_logging` is set in our own addon.

In Kodi 19, LOGNOTICE will go away and will be replaced with LOGINFO. LOGINFO is also supposed to be logged to the log there.

More info: https://forum.kodi.tv/showthread.php?tid=353818

**Comment by mediaminister** [comment]
I checked, LOGNOTICE is still in the Kodi master branch and still works:

https://github.com/xbmc/xbmc/blob/master/xbmc/utils/log.cpp#L248

**Comment by michaelarnauts** [comment]
This has been fixed in #214
