### ISSUE TITLE
Profile is not saved

### ISSUE THREAD

**Issue by ngaro** [add-ons/plugin.video.vtm.go#195]
When starting the addon it correctly fetches a list of video's and it's possible to watch a video after logging in.

But: The addon doesn't seem to remember this profile, it has to be entered again every time a video is being watched. The profile is immediately forgotten. (Even when still in the plugin, for the next video you need to login again)

I have tried this with the setting "Altijd het huidige profiel gebruiken" both turned on and off. Same result.

* OS: LibreELEC 9.2.1 RPI2.arm
* KODI: 18.6 Git:newclock5_18.6-Leia

My profile is a email address of 28 chars with only chars from the latin alphabet, `@` and `.`
The password also only contains chars from the latin alphabet and has a length of 6 chars.

Logging in on the VTMgo website (using a browser on a different system) works fine (with both profiles).

Barely related, but in case code is being reused: This problem does not appear with the vrtnu addon. (Same mail address is being used but a stronger password).

**Comment by ngaro** [comment]
After a a bit of messing around i found a workaround and the probable cause of the bug.

It does not seem to happen when you:
* Start a video
* Login
* Stop the video immediately once it starts playing
* Exit the plugin
* Enter the plugin again

Probably the bug is caused (I didn't read the code, consider this a "educated guess") because 2 different functions are used for logging in and saving the profile. I assume not everywhere the first function is called the 2nd one is also called. I assume this could be fixed by letting the first function call the other.
(Again this is only a guess based on the symptoms)

**Comment by michaelarnauts** [comment]
I could not reproduce it exactly as indicated above, but I do see an issue when you use the Add-on for the first time, and try to play an item, it will then ask the credentials, but it will not ask you to pick a profile. The credentials will be saved however. The next time the addon is used, it correctly asks for your profile, and it works as normal here.

**Comment by michaelarnauts** [comment]
@ngaro Could you try by installing this zip https://github.com/add-ons/plugin.video.vtm.go/archive/profile-fix.zip ?
