### ISSUE TITLE
Vtm 1 2 3 4 

### ISSUE THREAD

**Issue by Dominiquedb** [add-ons/plugin.video.vtm.go#204]
Just a heads-up in case you where not yet aware.
 Starting tomorrow the dpg media channels will change their names https://www.vrt.be/vrtnws/nl/2020/08/10/verandering-bij-vtm-zenders/

**Comment by dagwieers** [comment]
It was actually today, but the add-on worked fine regardless. Nevertheless a new release was made to update a few minor things.
Thanks for reporting ;-)
