### ISSUE TITLE
Inloggen lukt niet

### ISSUE THREAD

**Issue by DriesBru** [add-ons/plugin.video.vtm.go#223]
**Describe the bug**
De add on installeren lukt, maar eens ik mijn paswoord ingegeven heb krijg ik 'vtm go fout - check log voor meer info' 

**To Reproduce**
1. Add on installeren (via zip of rechtreeks in kodi) 
2. Mailadres en paswoord invullen 
3. Launch add on

**Expected behavior**

**Screenshots**
Inloggen en kunnen afspelen. 

**System**
 - Addon version: 1.1.4
 - Kodi version: 18.8
 - Inputstream adaptive version:
 - Operating System: LibreElec
 - Special Hardware: RPI

**Additional context**

**Comment by michaelarnauts** [comment]
Wat staat er in de log dan? Via de add-on Kodi Log uploader kan je die uploaden of bekijken.

**Comment by mediaminister** [comment]
Lijkt een algemeen probleem. VTM heeft een url gewijzigd. De authentication status test wordt trouwens geskipt.

**Comment by mediaminister** [comment]
@DriesBru Volgende update zou het loginprobleem moeten oplossen, kan je dit eens testen? [plugin.video.vtm.go-1.1.4-login-4e2a973.zip](https://github.com/add-ons/plugin.video.vtm.go/files/5413546/plugin.video.vtm.go-1.1.4-login-4e2a973.zip)

**Comment by DriesBru** [comment]
Inderdaad opgelost @mediaminister , merci!
