### ISSUE TITLE
Use "Recommendations, Movies and Series" instead of the Catalog

### ISSUE THREAD

**Issue by michaelarnauts** [add-ons/plugin.video.vtm.go#230]
The underlying catalog isn't exposed anymore directly on the VTM GO website or app, but so-called storefronts are used right now. We still use it for a A-Z listing (what isn't available on the real app/website).

Since the content in Recommendations and Catalog is mainly the same, we should stick with Recommendations (as displayed on the Home tab), Movies and Series.

Actually, like we did in the Streamz addon.

**Comment by dagwieers** [comment]
Does this mean the [A-Z] listing will be removed?

**Comment by michaelarnauts** [comment]
No, I would like to keep that.
