### ISSUE TITLE
488 Client Error: Unknown for url: https://api.vtmgo.be/vtmgo/live

### ISSUE THREAD

**Issue by piejanssens** [add-ons/plugin.video.vtm.go#231]
**Describe the bug**
Error shown when trying to access 'kanalen'. 
[kodi.log](https://github.com/add-ons/plugin.video.vtm.go/files/5429460/kodi.log)

**To Reproduce**
1. Log in
2. Open VTM Go add-on
3. Open 'kanalen'

**Expected behavior**

**Screenshots**

**System**
 - Addon version: 1.1.5
 - Kodi version: 18.8
 - Inputstream adaptive version: 0.5.1
 - Operating System: OSMC
 - Special Hardware:  Vero4K+

**Additional context**
I don't have this issue on my other Vero.

**Comment by michaelarnauts** [comment]
488 usually indicates that you don't have a profile specified. Do you have a profile visible in your settings? Maybe something is wrong with the login?

**Comment by piejanssens** [comment]
It worked all of a sudden. I switched "always use this profile" then opened 'kanalen', then switched it off.
