### ISSUE TITLE
Kodi integration: launching tv series from library fails while it works using the addon

### ISSUE THREAD

**Issue by badoneti** [add-ons/plugin.video.vtm.go#245]
**Describe the bug**
TV series are playing when launched from the vtmgo add-on. I setup also the kodi integration. But launching tv series from kodi tv series library fail.

**To Reproduce**
1. Launch the tv series episode (eg. boer zkt vrouw) from VTM GO and verify this works (e.g. inputstream adaptive fix)
2. Launch the same episode from the kodi tv library
3. Does not launch the stream (suspect failure loading commercials)

**Expected behavior**
Launch the episode as it works from the add-on

**System**
 - Addon version: 1.2.0
 - Kodi version: 18.9 leia
 - Inputstream adaptive version: zip downloaded here
 - Operating System: LibreElec

**Comment by michaelarnauts** [comment]
Can you give me a logfile? Preferably with debug logging activated first.

**Comment by badoneti** [comment]
Here is the log; 
[01_KODI.log](https://github.com/add-ons/plugin.video.vtm.go/files/5724400/01_KODI.log)
failure loading via kodi library < 14:00
same episode loading via vtmgo addon > 14:00

**Comment by michaelarnauts** [comment]
Heb je de stappen op [de wiki](https://github.com/add-ons/plugin.video.vtm.go/wiki/Integratie-met-Kodi) gevolgd, het path exact overgetypt met een `/` op het einde, en **Local information only** aangeduid? Het lijkt dat er dingen op IMDB opgezocht worden, wat niet de bedoeling is.

**Comment by michaelarnauts** [comment]
@badoneti ik heb je comment verwijderd omdat je wachtwoord in die debug log stond (was ook een foutje, die werd niet gefilterd in de log), best zo snel mogelijk je wachtwoord aanpassen dus.

Zou je nog eens kunnen proberen met deze versie? https://github.com/add-ons/plugin.video.vtm.go/archive/master.zip Deze lost een probleem op met authenticatie bij de library, en dat je wachtwoord niet in de log komt :)

Best eerst je toegevoegde path wegdoen in Kodi, daarna in de Add-on, bij Kodi-bibliotheek kiezen voor "Bibliotheek opschonen", en dan de folders opnieuw toevoegen zoals beschreven in https://github.com/add-ons/plugin.video.vtm.go/wiki/Integratie-met-Kodi

**Comment by badoneti** [comment]
Bedankt in elk geval voor deze kodi library integratie, een top-feature!
Ik heb de wiki correct gevolgd met het pad etc.
De IMDB informatie wordt erbij gehaald via een andere plugin, voor films werkt dat overigens prima samen.

**Comment by michaelarnauts** [comment]
> Bedankt in elk geval voor deze kodi library integratie, een top-feature!
> Ik heb de wiki correct gevolgd met het pad etc.
> De IMDB informatie wordt erbij gehaald via een andere plugin, voor films werkt dat overigens prima samen.

Hmm, oké. En werkt het wel met die nieuwere versie? Ik had het hier geprobeerd, en het werkte wel gewoon prima. Ik zie in je log (buiten veel scans) wel geen request op iets af te spelen vanuit de library...

**Comment by badoneti** [comment]
Ja het werkt terug na de library te hebben refreshed (met de local info only optie).
Zette ik nadien terug de IMDB integratie op werkt het ook nog steeds. 
Mss was er iets met de skin waardoor de play command niet doorkwam.

**Comment by michaelarnauts** [comment]
Oké! Bedankt om het te melden allesinds!
