### ISSUE TITLE
Audio track not resuming after intermediate stop of the stream

### ISSUE THREAD

**Issue by pl0ng** [add-ons/plugin.video.vtm.go#249]
**System**
R-Pi 3b, OSMC OS, Kodi Leia
VTMgo 1.2.2

**Describe the bug**
If you stop (full stop, not pauzing) a stream at a given point and want to resume at the given timestamp later on, the audio track is no longer resumed, only the video.
Restarting the stream or the OS entirely doesn't resolve the issue.

**To Reproduce**
1. Start a given stream. This happened in our case with movies 'Bagage claim' and 'The Christmas note' for example.
2. Full stop the stream
3. Restart the stream. Audio is no longer there

**Comment by michaelarnauts** [comment]
I have also noticed this. It seems to be an issue in Inputstream Adaptive. It also occurs when you start from the beginning, and seek past the first advertisement break.

**Comment by michaelarnauts** [comment]
Met Inputstream Adaptive 2.6.16, en de VTM GO Addon 1.2.7 zou dit in orde moeten zijn.
