### ISSUE TITLE
Credentials are not stored

### ISSUE THREAD

**Issue by bcnx** [add-ons/plugin.video.vtm.go#254]
**Describe the bug**
I need to re-enter the vtm go credentials on a regular basis.

**To Reproduce**
Just use the addon and the request for credentials reappears.

**Expected behavior**
Just a onetime question.

**Screenshots**

**System**
 - Addon version: latest
 - Kodi version: latest
 - Inputstream adaptive version:
 - Operating System: Libreelec
 - Special Hardware: rpi

**Additional context**

**Comment by dagwieers** [comment]
I have not experienced this. I expect that you may have a storage issue (i.e. SD card is broken and does not write credentials).

Is there anything in the Kodi debug or system logs?

**Comment by bcnx** [comment]
Hi, 

we had it several times a day, but the problems seems to have disappeared by itself. The SD card is new, but it could be a dud. I will monitor the problem for the next days, we use the AddOn everyday anyway.

I also have a problem that paused shows loose audio, but I will create another issue for that,

Cheers,

BC
