### ISSUE TITLE
LibreElec Matrix - Stream doesn't start.

### ISSUE THREAD

**Issue by keiem** [add-ons/plugin.video.vtm.go#255]
**Describe the bug**
Streams don't start playing.  I see the video loading but suddenly it stops and the video never starts.

**To Reproduce**
1Selecting a episode in VTM-GO addon.

**Expected behavior**
A clear and concise description of what you expected to happen. I don't know if it is a problem with the addon or with LibreElec.  It's a Development LibreElec with Kodi Matrix.  VRT-NU works fine.
In the log I see Unsupported stream or Unable to select stream.

**Screenshots**

**System**
 - Addon version: 1.2.2+matrix.1
 - Kodi version: Matrix
 - Inputstream adaptive version: 2.6.6.2
 - Operating System: LibreElec
 - Special Hardware: Station M1 (rk3328 processor)
 - 
**Additional context**
Link to log file: http://ix.io/2N1H

**Comment by michaelarnauts** [comment]
I can see the https://dcs-vod.apis.anvato.net/vod/p/session/https://dpp-anvato-live.akamaized.net/eu/vod/10000001/19/06/28/10037142/video-4 in your log, so you might not have the latest VTM Go Add-on version, of you have disabled the proxy setting in the add-on settings.

**Comment by keiem** [comment]
Indeed, the proxy setting was turned off.  It was a complete fresh install to check if my problems with vtm-go are due to the khadas vim1 or because it's already running for a few years.  Now it seems on the station M1 the problems with freezing and black screens are gone. As the rk3328 and the S905 are mostly equal it will have something to do with leia vs matrix or a system that is to much contaminated during the years.

**Comment by michaelarnauts** [comment]
Have you manually turned the setting off? It should be on by default if I remember correctly...

**Comment by keiem** [comment]
As far as I know, I didn't, I did a fresh install and it didn't work from the start.  I didn't ask myself questions about that because I thought it was solves in version 1.2.2.  What I did was I installed 1.2.2 first, it didn't work, then I downgraded to the version form the bug reports.  It didn't work either.  Then I reinstalled 1.2.2 and made the log file.

**Comment by keiem** [comment]
I should check I switched back from my Station M1 to my Khadas VIM1.  On the Khadas VIM1 everything is fine, still the sound end freezing video issue on the beginnenin of the stream and after a commercial but for the rest is plays fine.

I will test it on the Station M1.

**Comment by eboelens** [comment]
Hi i have the same problem i think. The stream does not start or stops immediately at both VTM GO and TV Vlaanderen. VRT NOW works.
I came from Leia and went to Kodi 19 but now back to Leija with a completely fresh install.
What can I do please ?

**Comment by dagwieers** [comment]
@eboelens Is it possible your issue is related to the recent Widevine CDM update? The solution is to rollback to a previous Widevine CDM version. See: https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/437#issuecomment-836698949

**Comment by renaatdemuynck** [comment]
I can confirm that the Widevine rollback solutions works
