### ISSUE TITLE
Widget aspects

### ISSUE THREAD

**Issue by wardwygaerts** [add-ons/plugin.video.vtm.go#256]
I use widgets with the skin Arctic: Zephyr for my favorites of VRT Nu, VTM GO & Streamz. This looks very nice, but only VRT Nu is providing nice poster (portrait) formats. In VTM Go & Streamz, the images which are used are in landscape, so they are cutoff.
![IMG_20210129_123914](https://user-images.githubusercontent.com/7568498/106271113-4e34cc00-622f-11eb-9f32-75bbc4761511.jpg)
I also tried other aspects, but couldn't find any good one. There is a 'landscape' aspect, but then the skin is using the backdrop ffrom the show.

I saw on the VTM Go site, they do have portrait images for some stuff:
![image](https://user-images.githubusercontent.com/7568498/106271334-a4a20a80-622f-11eb-9ae0-f3983b5ce9d8.png)

Are thse portrait images available for all shows? Or is there another solution?

**Comment by dagwieers** [comment]
It seems that VTM GO only has the poster-format artwork for new content. Much like VRT NU, although VRT NU has been started doing this for a bit longer. That is why only the "Nieuw op VTM GO" section has poster-format artwork.

I expect this over time to be extended to all content.

**Comment by dagwieers** [comment]
I was looking into this and these are links to both artwork:
- https://images0.persgroep.net/rcs/oWrrS2jZ6lyZAK9PkKEo4iprTR4/diocontent/181478836/_fitwidth/300?appId=038a353bad43ac27fd436dc5419c256b&quality=0.8
- https://images0.persgroep.net/rcs/t8uUPtAA9hR0eZjpbZNk9J7WFlc/diocontent/181478835/_fitwidth/426?appId=038a353bad43ac27fd436dc5419c256b&quality=0.8

So `426` means **426x240** (wide screen, 240p) and `300` means **300x450** (poster or teaser__img).

However I cannot find these references from the existing payload, I can only see it as part of the HTML at the VTM GO website. Maybe the add-on uses a different API for this now?

**Comment by michaelarnauts** [comment]
The API doesn't provide poster images at the moment, only for the lists at the homepage, that being said, I've fixed a few misalligned types in #269 that has been merged recently. You should try with the latest code if this has improved. You'll want to select landscape artwork for VTM GO however. Before, it would show the fanart (without the program title), now it'll select the correct landscape artwork.

**Comment by michaelarnauts** [comment]
You can try with these versions but you won't have poster art yet for all programs, but landscape should be fine now. I'll look into this a bit further, but if they have artwork for all programs, the links that @dagwieers has documented above could be used to fetch the right artwork.

For Leia: https://github.com/add-ons/plugin.video.vtm.go/files/6175881/plugin.video.vtm.go-1.2.5-dev-master-702c9c0.zip

For Matrix: https://github.com/add-ons/plugin.video.vtm.go/files/6175882/plugin.video.vtm.go-1.2.5-dev%2Bmatrix.1-master-702c9c0.zip

**Comment by michaelarnauts** [comment]
The API only provides this info:

```
{
  "id":"d7e68d3d-b6c9-498e-b41e-95590159b75f",
  "name":"Lisa",
  "description":"Lisa droomt van een carri\u00e8re in een hip marketingbureau. Met haar intelligentie en creativiteit heeft ze alles in huis om het te maken, maar haar extreme schuchterheid zorgt ervoor dat ze niet vooruit kan. ",
  "bigPhotoUrl":"https://images0.persgroep.net/rcs/fSxmGcAdY57xfktDX3y2aJeHT_o/diocontent/181478833/_fitwidth/1400?appId=038a353bad43ac27fd436dc5419c256b&quality=0.8",
  "mediumPhotoUrl":"https://images2.persgroep.net/rcs/VKZKjpblldZbpb4cpCtqotSJvsU/diocontent/181478833/_fitwidth/1280?appId=038a353bad43ac27fd436dc5419c256b&quality=0.8",
  "smallPhotoUrl":"https://images4.persgroep.net/rcs/Sgc_4c8zX1x0ZaMQcxodHKveZVU/diocontent/181478833/_fitwidth/426?appId=038a353bad43ac27fd436dc5419c256b&quality=0.8",
  "teaserImageUrl":"https://images2.persgroep.net/rcs/Dt-mDTxJKfLHoeKaZcrfonPqSXU/diocontent/200218223/_fitwidth/426?appId=038a353bad43ac27fd436dc5419c256b&quality=0.8",
  "activeSeasonIndex":1,
  "activeEpisodeId":"27c687ca-fa81-4c1a-86a4-39d1e0ca488a",
  "watching":false,
  "channelLogoUrl":"https://lfvp-api.dpgmedia.net/static/images/logos/vtm-4992052d12c6e415cd42d1aaa43f42a7.png",
...
```

I don't get the image with the `300` size. Also, I can't just change the URL, since the identifier after `rcs/` is unknown.

**Comment by wardwygaerts** [comment]
Landscape is indeed better! I don't see any difference for the posters, but I probably have not the correct programs in my list

**Comment by wardwygaerts** [comment]
The first row is setup as Landscape, the seconds as Poster, but it seems that it takes the same images, althouh I see on the homepage some Posters:
![IMG_20210322_215446](https://user-images.githubusercontent.com/7568498/112119244-7b618300-8bbd-11eb-9e53-651595d9f189.jpg)

https://images1.persgroep.net/rcs/rFTzdeY2F95uoOYeghEtS9YYDdw/diocontent/200018341/_fitwidth/300?appId=038a353bad43ac27fd436dc5419c256b&quality=0.8
https://images2.persgroep.net/rcs/vSNdGKEbw5ePTdqu3QxFdmAftEg/diocontent/200452825/_fitwidth/300?appId=038a353bad43ac27fd436dc5419c256b&quality=0.8
https://images0.persgroep.net/rcs/rafXcEsFe4XPSXIoWh6mF6a8M8A/diocontent/182311313/_fitwidth/300?appId=038a353bad43ac27fd436dc5419c256b&quality=0.8

**Comment by michaelarnauts** [comment]
> The API doesn't provide poster images at the moment, only for the lists at the homepage

I don't use the results from the homepage, since they are limited to 40 results and incomplete. The full API doesn't do posters, so for now, this is the best I can do.

**Comment by michaelarnauts** [comment]
As long as there are no portrait images in the API result, there isn't much we can do about this.
