### ISSUE TITLE
the refresh rate is constantly changing during advertising interruption

### ISSUE THREAD

**Issue by Thomaskito** [add-ons/plugin.video.vtm.go#263]
> **Describe the bug**

When playing the advertising interruption the refresh rate is constantly changing.
(it go from 25, 30 and 50 hz)
So I keep getting a black screen, with pieces of the advertising interruption in it.
Sometimes after the advertising interruption the sound of the video is gone.

Only if i set kodi settings to "whitelist 1080p 50hz" as the only one will the ad play normally.
but this is detrimental to other addons and this issue is only with vtmgo.

is it not possible to have the vtmgo addon only run at 50hz?

**To Reproduce**
1.play any video from vtmgo
2. wait for the advertising interruption

**Expected behavior**
keeping the same refresh rate during the advertising interruption (50hz) 

**System**
 - Addon version: 1.2.3
 - Kodi version: 18.9
 - Inputstream adaptive version: latest 
 - Operating System: coreelec
 - Special Hardware :minix u22 / 4k oked tv

**Comment by michaelarnauts** [comment]
This is probably due to the Kodi setting to match the refresh rate to the content. Since the ads are all different files (with, I assume, different fps), this will make Kodi do frequent changes of refresh rate.

**Comment by Thomaskito** [comment]
that I haven't thought of that.
if I turn this off, the ad will indeed play normally.
it is probably not possible, just turn this off in the vtmgo addon?
so that other addons can use the "match the refresh rate to the content" option
without having to change it every time in the settings

**Comment by michaelarnauts** [comment]
I guess there is nothing that can be done here. The ads are different streams with different refresh rates. The behaviour of Kodi is correct when you have enabled that setting.

It's a global setting unfortunately.
