### ISSUE TITLE
Bug: Poster fanart seems incorrect

### ISSUE THREAD

**Issue by vermope** [add-ons/plugin.video.vtm.go#268]
Could it be that the poster fanart is set with the wrong metadata? When using widgets and choosing poster format it gives me landscape art instead of poster art.  
Some screenshots to see the difference with GoPlay:
https://imgur.com/a/1lgr8Gt

**Comment by michaelarnauts** [comment]
You are right. I think I'm using the wrong keys to specify covers or posters.
One issue however is that for some API calls I only get a landscape image, and for other API calls, i get a poster image. I'm not sure how the skin will render this.

It looks like you are using Arctic Horizon, how did you create these categories? Is that a custom menu item with multiple widgets that all call a specific path in the addon?

**Comment by vermope** [comment]
I'm indeed using Arctic Horizon. The widget is build trough the addon itself: Widgets Home > Shortcuts > Customize > Video Addon > VTMGO > Recommendations > Aanbevolen voor jou (Aspect = Poster) (Label = Trending VTM GO) (Sort = Random)

So it seems it's using an official category from the VTM GO app (Aanbevolen voor jou)

**Comment by vermope** [comment]
I also think that maybe fanart and landscape art are mixed up. 
fanart = landscape without logo or movie title
landscape = landscape fanart that contains recognizable characters or props from the movie and a logo

Ref: https://kodi.wiki/view/Artwork_types#landscape

**Comment by michaelarnauts** [comment]
[plugin.video.vtm.go-1.2.5-dev-artwork-9c76f1a.zip](https://github.com/add-ons/plugin.video.vtm.go/files/6171835/plugin.video.vtm.go-1.2.5-dev-artwork-9c76f1a.zip) (Leia)
[plugin.video.vtm.go-1.2.5-dev+matrix.1-artwork-9c76f1a.zip](https://github.com/add-ons/plugin.video.vtm.go/files/6171836/plugin.video.vtm.go-1.2.5-dev%2Bmatrix.1-artwork-9c76f1a.zip) (Matrix)

**Comment by vermope** [comment]
Tested, the same issue remains.

**Comment by michaelarnauts** [comment]
Je gaat voor VTM Go de landscape aspect moeten gebruiken. Er zijn geen poster images in de API. In de huidige versie geeft dit de de fanart zonder text, maar dat zou opgelost moeten zijn in die versie hierboven.

**Comment by vermope** [comment]
Ok, ik heb mijn menu structuur intussen aangepast. Bedankt om dit te bekijken!
