### ISSUE TITLE
401 client error: Unauthorized for url

### ISSUE THREAD

**Issue by mcmurdy** [add-ons/plugin.video.vtm.go#271]
**Describe the bug**
After opening VTM GO addon i get an error: 401 Client Error: Unauthorized for url.... 

**To Reproduce**
1. Start Kodi
2. Install VTM Go Addon
3. Add login details in settings
4. Start VTM Go addon

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/11727066/111912535-61fbf200-8a6a-11eb-8f10-50ca79c83198.png)

**System**
 - Addon version: 1.2.4
 - Kodi version: 19
 - Inputstream adaptive version: 3.0.1
 - Operating System: (Windows / Mac OS / Android / LibreElec / OSMC / ...) OpenSuse 15.2
 - Special Hardware: (RPI / Vero4K+ / ...)

**Additional context**

[Debug-log](http://paste.kodi.tv/finikahepe)

**Comment by michaelarnauts** [comment]
This has been fixed in de latest master branch. 

You can try with the version below.

https://github.com/add-ons/plugin.video.vtm.go/pull/270#issuecomment-803382728

**Comment by michaelarnauts** [comment]
Has been fixed in 1.2.5.
