### ISSUE TITLE
Geen audiospoor na update Inputstream 2.6.14.1 CoreElec Kodi 19

### ISSUE THREAD

**Issue by kengithub9** [add-ons/plugin.video.vtm.go#274]
Ik heb problemen (geen audio) sinds ik in CoreElec versie 2.6.14.1 geïnstalleerd heb.
Met versie 2.6.7.3. werkte alles wel.

Wat ik ook nog steeds heb is dat hij net na het begin even een zwart beeld geeft, ook tijdens de reclames, heb gemerkt dat het komt door de framerate wisselingen.

Hoe kan ik de inputstream versie terugzetten, de zip die je op github vindt kan niet geïnstalleerd worden?

**System**
 - Addon version: 1.25
 - Kodi version: 19.0
 - Inputstream adaptive version: 2.6.14.1
 - Operating System: CoreElec 19.1rc4
 - Special Hardware: Beelink GT-King

**Comment by boskabouter01** [comment]
Kan hetzelfde probleem bevestigen. Na installatie van Inputstream Adaptive version 2.6.13.1 werkt het geluid terug.
Instellingen | Add-Ons |  VTM GO |  Afhankelijkheden | Inputstream Adaptive | Versies | selecteer vorige versie.
(De aangepaste versie nummer verschijnt niet in het bovenliggend dialoog venster !)

**Comment by kengithub9** [comment]
Helaas kan ik geen andere versie selecteren om de inputstream te wijzigen.

**Comment by michaelarnauts** [comment]
Kan je een issue openen op https://github.com/xbmc/inputstream.adaptive hiervoor? Vermeld best wat je wil afspelen, en op welke versie het issue zich voordoet en waar niet. Ik kan wel zorgen dat de devs van inputstream adaptive een account van VTM GO hebben om te kunnen reproduceren.

Ik heb zelf niet veel tijd om het uit te pluizen, maar Glennguy is ongelofelijk goed bezig om IA te verbeteren!

**Comment by badoneti** [comment]
is het mogelijk om tijdelijk een downgrade te doen van IA? Via the dependencies etc lukt dat alvast niet bij mij.
Heb geen optie gevonden die me toelaat versie te kiezen 
Instellingen | Add-Ons | VTM GO | Afhankelijkheden | Inputstream Adaptive | **Versies | selecteer vorige versie.**

**Comment by kengithub9** [comment]
Voor iedereen met het probleem, hier een oude versie van de inputstream die wel audio geeft.
[inputstream.adaptive-2.6.13.1.zip](https://github.com/add-ons/plugin.video.vtm.go/files/6409566/inputstream.adaptive-2.6.13.1.zip)

**Comment by dagwieers** [comment]
@kengithub9 Het is handig als je een ticket opent bij ISA, je dat hier ook vermeldt: https://github.com/xbmc/inputstream.adaptive/issues/667#issuecomment-830575225

**Comment by michaelarnauts** [comment]
Het lijkt erop dat het toch nog niet gefixt is met die change.

**Comment by michaelarnauts** [comment]
Met Inputstream Adaptive 2.6.16, en de VTM GO Addon 1.2.7 zou dit in orde moeten zijn.

**Comment by michaelarnauts** [comment]
Can you confirm you have installed the 1.2.7 version of the VTM Go Addon from zip? The version in the repo isn't updated yet.

Have you also enabled the proxy setting in the add-on expert settings? It should be enabled.

To be sure, can you state the version of IA and VTM Go?

**Comment by badoneti** [comment]
I confirm using the 1.2.7 version of the VTM Go Addon from zip with IA 2.6.16.1
After fiddling a little and a few restarts, it seem working again after activating the MPEG-Dash setting in VTM Go addon settings (I believe it was previously mentioned being solved)
Yet when scrolling forward over ads, it sometimes works and sometimes freezes for 30sec showing 100% loaded icon.
In some cases it then continues playing, sometimes kodi crashes and restarts.

**Comment by michaelarnauts** [comment]
Thanks for confirming that it works again. Skipping ads is always tricky in Inputstream Adaptive, due to the many period switches, nothing that can be done within the Add-on. I suggest to just get something from the fridge during the ads :grinning: 

The proxy needs to be enabled for now. Some issues that the proxy originally tried to solve are fixed already, but not all. The setting is there in case it needs to be disabled for a future Inputstream Adaptive update.
