### ISSUE TITLE
Error log pop-up every hour

### ISSUE THREAD

**Issue by Rvhalewyn** [add-ons/plugin.video.vtm.go#277]
**Describe the bug**
See screen shot for error descriotion
**To Reproduce**
1. Playing anything, not necessarily VTM 
2. Error pop-up comes up out of the blue, every 60 min,  about something going wrong between Vtm add-on and IPTV Manager. 
3.Playing goes on on the background 

**Expected behavior**
No disturbance by pop-up
Normal coordination between VTM and IPTV Manager 

**Screenshots**
https://www.dropbox.com/sh/r0fefj30yz0vh3b/AABP7xKsLV6yNNq8VoQiqLlEa?dl=0
**System**
 - Addon version: 1.2.5
 - Kodi version:18.9
 - Inputstream adaptive version:2.4.6.1
 - Operating System: (Windows / Mac OS / Android / LibreElec / OSMC / ...)
 - LubreElec
 - Special Hardware: (RPI / Vero4K+ / ...) no

**Additional context**
Happened today for the first time. No recent system changes or updates.

**Comment by dagwieers** [comment]
VTM GO made changes to authentication and the add-on no longer works without changes. Because of this IPTV Manager triggers this when it updates EPG information.

We will have to wait for a new release that fixes the authentication issue.

**Comment by michaelarnauts** [comment]
@Rvhalewyn this should have been fixed with the latest 1.2.7 release (and probably also with 1.2.6), make sure you use the correct password, since DPG has changed them recently.
