### ISSUE TITLE
Can't install V1.2.6 in kodi Matrix

### ISSUE THREAD

**Issue by coreflake1** [add-ons/plugin.video.vtm.go#279]
**Describe the bug**
Can't install V1.2.6 in kodi Matrix
"the dependancy on xbmc.python version 2.26.0 could not be statisfied"
**To Reproduce**
1.Download V1.2.6 from git
2.Try to install in kodi Matrix
3.Get error on failing dependancy 

**Expected behavior**
Install plugin => plugin installs because it's dependand on Pyhton V3 (which is used in Kodi Matrix).

**System**
 - Addon version: 1.2.6
 - Kodi version: 19.0
 - Inputstream adaptive version: 2.6.13.1
 - Operating System: LibreElec 
 - Special Hardware: RPI4

**Comment by coreflake1** [comment]
Just to make clear : 
I downloaded the matrix version of the plugin from github.

**Comment by mediaminister** [comment]
I can confirm the plugin.video.vtm.go-1.2.6+matrix.1.zip on Github contains the wrong Python ABI version.

**Comment by frankdpGH** [comment]
Hi, Thanks a lot for your fast responses!!! Had the same problem with Github release but the last zip file above is working now on android arm8.

**Comment by michaelarnauts** [comment]
My mistake, there is an issue with the packaging script to create the zips, and I forgot to fix that. I've updated the release.

Thanks for opening the issue!
