### ISSUE TITLE
VTM go doesn't work in kodi matrix anymore

### ISSUE THREAD

**Issue by Warsnake2** [add-ons/plugin.video.vtm.go#281]
Last available version on kodi repo is 1.2.5 and after manually updating to 1.2.6 it has the same issue. VTM go add-on van be opened but won't load any page after the Startpage. Error message shown: 401 Client Error: Unauthorized for URL: https://lfvp-api.dpgmedia.net/VTM go/my-list. When opening 'mijn lijst'. Or https://lfvp-api.dpgmedia.net/VTM go/catalog?Pagesize=2000 when opening 'a-z'

**Comment by Warsnake2** [comment]
Seems to be related to the authorization issues in previously recorded tickets.

**Comment by mediaminister** [comment]
There is a workaround:
- Disable 'Always use the current profile' in VTM GO add-on settings
- Restart de VTM Go Add-on
- Open a program listing
- Enable 'Always use the current profile' again if needed

**Comment by BIoob** [comment]
unfortunately the workaround doesn't work for me. I wasn't using "Always use the current profile" before this error started.

Enabling / disabling it doesn't help.

**Comment by mediaminister** [comment]
Make sure you have version 1.2.6, the workaround should work. If not, provide a full debug log: https://kodi.wiki/view/Log_file/Easy

**Comment by Warsnake2** [comment]
@mediaminister The workaround woes work for me. Had to reset my password on the VTM Go website as well as at first it kept saying that the credentials were invalid. Thank you for the help.
PS: Might be helpfull to add the workaround to the Wiki.

**Comment by mediaminister** [comment]
I'm working on a better fix.
