### ISSUE TITLE
401 cliënt eror

### ISSUE THREAD

**Issue by pieterVE** [add-ons/plugin.video.vtm.go#283]
**Describe the bug**

401 cliënt eror: unautherized for url https://lfvp-api.dpgmedia.net/vtmgo/storefronts/9620cc0b-0f97-827dcfd0b227

**To Reproduce**
1.open vtm go
2.select "aanbevelingen"

**System**
 - Addon version:1.2.6
 - Kodi version:18.9.0
 - Inputstream adaptive version:2.4.7.1
 - operating sys: LibreElec 9.2.6
 - Special Hardware: RPI4

**Comment by mediaminister** [comment]
Please test this zip package, it should fix your problem.
For Kodi 18 Leia:
[plugin.video.vtm.go-1.2.6-auth-808778c.zip](https://github.com/add-ons/plugin.video.vtm.go/files/6437267/plugin.video.vtm.go-1.2.6-auth-808778c.zip)

For Kodi 19 Matrix:
[plugin.video.vtm.go-1.2.6+matrix.1-auth-808778c.zip](https://github.com/add-ons/plugin.video.vtm.go/files/6437266/plugin.video.vtm.go-1.2.6%2Bmatrix.1-auth-808778c.zip)

**Comment by GunterO** [comment]
Works, thanks!

**Comment by pieterVE** [comment]
Perfect, problem solved!

Dankjewel!!!
Pieter

Op do 6 mei 2021 om 21:48 schreef mediaminister ***@***.***>

**Comment by JelleDeMoor** [comment]
Geprobeerd op Matrix: werkt!

**Comment by henkson** [comment]
Ik krijg ook een http 401 response bij opstarten van Kodi:
InvalidTokenException: 401 Client Error: Unauthorized for url: https://lfvp-api.dpgmedia.net/vtmgo/catalog?pagesize=2000

Is dat hetzelfde probleem? 
Ik gebruik een mxq android box, installeren van een .zip is niet evident, wordt dit in de volgende versie van de plugin opgelost?

**Comment by dagwieers** [comment]
Je moet je account gegevens aanpassen in de add-on. Je hebt hierover een mail gekregen van DPG Media. Bij mij waren alle accounts met hetzelfde email samengevoegd met het paswoord van mijn HUMO account.

**Comment by henkson** [comment]
@dagwieers Bedankt voor je antwoord. Ik heb geen mail gezien van DPG Media (ook niet bij spam). Maar ik heb (via computer) een nieuw wachtwoord gekozen, en dat dan ook in de add-on aangepast. Nu lijkt alles weer te werken.

**Comment by bertvandepoel** [comment]
@mediaminister de 808778c file die je linkt, is dat de gewone 1.2.6 release (die run ik al op leia, met dezelfde problemen als bovenaan beschreven) of is heeft die een paar extra commits?

**Comment by mediaminister** [comment]
Neen, de files hebben een extra commit die ongeldige tokens op voorhand verwijdert, momenteel zit de oplossing al in de master branch: https://github.com/add-ons/plugin.video.vtm.go/commit/77e616b5d10fd606b82cadac9f39bf7088cde2f9

**Comment by michaelarnauts** [comment]
Dit zou ondertussen in orde moeten zijn. De 1.2.7 release heeft ook nog een betere detectie van foute tokens.
