### ISSUE TITLE
Kodi crasht na hervatten uitzending

### ISSUE THREAD

**Issue by henkv1** [add-ons/plugin.video.vtm.go#295]
Als ik de uitzending van Rupel '1x08. De laatste uitweg' probeer te hervatten vanaf 00:40:03 crasht kodi direct.

Informatie over het systeem:
Hardware: Raspberry Pi 3 (maar ik heb hetzelfde probleem op een Raspberry Pi 4 met dezelfde software stack)
OS: Arch Linux ARM
Kodi: 19.1-8
Kernel: 5.10.50-2-ARCH
Inputstream adaptive: 2.6.22
VTM GO addon: 1.2.10+matrix.1

**Comment by henkv1** [comment]
[kodi_crashlog-20210722_111932.log](https://github.com/add-ons/plugin.video.vtm.go/files/6861236/kodi_crashlog-20210722_111932.log)

**Comment by michaelarnauts** [comment]
I've just tried on my system and it works fine.

* Ubuntu Linux 20.04.2
* Kodi 19.1
* IA 2.6.17
* Widevine 4.10.2209.0

I'll try updating IA now to the latest version and recheck.

**Comment by michaelarnauts** [comment]
@henkv1 I've updated to IA 2.6.22 (latest version in the PPA), and it worked fine. I've played Rupel 1x08 and skipped until around 40:10, playback went fine. I've stopped the stream. Started it again, and selected to resume from 40:10. The playback started fine again.

I'm unable to test on a RPI right now, I only have access to a Kodi on my laptop.

I assume you've tried rebooting your RPI? A crash like this is definitely an issue in IA or Kodi itself, the Add-on isn't doing anything during playback.

**Comment by henkv1** [comment]
OK, I'll try different versions of IA and Kodi.

**Comment by henkv1** [comment]
I can indeed confirm that there is an issue with the Kodi version of Arch Linux Arm. The issue was introduced in kodi-rpi-19.1-4, so kodi-rpi-19.1-3 works fine. 
I am not sure if this issue is present in other distributions for the Raspberry Pi as well.

**Comment by henkv1** [comment]
The issue is caused by the hardware acceleration on the Raspberry Pi, introduced by this patch: https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/multimedia/ffmpeg/patches/rpi/ffmpeg-001-rpi.patch (for LibreElec) or https://github.com/popcornmix/xbmc/blob/gbm/tools/depends/target/ffmpeg/0001-rpi-Add-hevc-acceleration.patch (Arch Linux Arm)
Disabling hardware acceleration fixes this as a workaround.

**Comment by michaelarnauts** [comment]
@henkv1 thanks for verifying, i'll close the issue here since there's nothing we can do unfortunately.
