### ISSUE TITLE
"404 Client Error: Not Found for url: " when opening VTM Go "A-Z" in main menu

### ISSUE THREAD

**Issue by Bart80-1** [add-ons/plugin.video.vtm.go#307]
**Describe the bug**
In VTM Go, getting error message "404 Client Error: Not Found for url: https://lfvp-api.dpgmedia.net/vtmgo/catalog?pageSize=2000" when opening "A-Z" in VTM Go's main menu.

**To Reproduce**
1.Go to the plugin (via add-ons/VTM Go)
2.In main menu, choose "A-Z"
3.Error message appears

**Expected behavior**
Alphabetical list of available programs.

**Screenshots**
On Raspberry2b:
![IMG_ 20211110_185207](https://user-images.githubusercontent.com/88739672/141178425-e7ec87bf-6eb3-4d00-bb12-b9ac70ee87e3.jpg)
On Raspberry4:
![IMG_ 20211110_194528](https://user-images.githubusercontent.com/88739672/141178460-5f154f50-6e35-4879-9070-b08016e45b76.jpg)

**Logs**
[kodi vtm go.log](https://github.com/add-ons/plugin.video.vtm.go/files/7515375/kodi.vtm.go.log)

**System**
I experience this issue on 2 different systems, an RPI2 and an RPI4.
RPI2:
 - Addon version: 1.2.12
 - Kodi version: 18.9.0
 - Inputstream adaptive version: (Don't have this information at hand now - if important please tell me).
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...): LibreElec 9.2.8
 - Special Hardware (RPI / Vero4K+ / ...): RPI2.

RPI4:
 - Addon version: 1.2.12+matrix.1
 - Kodi version: 19.1
 - Inputstream adaptive version: 19.0.0.1
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...): LibreElec 10.0.0
 - Special Hardware (RPI / Vero4K+ / ...): RPI4.

**Comment by reneverlinden** [comment]
rené verlinden
since 8/11 the same error 404 and the same messages as above  occur  when I'm trying to open A-Z in VTM GO on Raspberry Pi 4, Libreelec Kodi-Matrix,, despite an update of Widevine. No problems with the VTM- live streams.

**Comment by jelledp** [comment]
I have the same error.

**Comment by lebeno** [comment]
Same problem here. As a temporary workaround I logged in on the VTM Go website, and added some extra programs to "Mijn lijst"

**Comment by dwalerXIII** [comment]
Same problem here

**Comment by faelterman** [comment]
Same problem on Nvidia Shield Pro and on google tv

**Comment by michaelarnauts** [comment]
The A-Z api endpoint has been removed. There is also no A-Z listing in the Android app. The correct way forward will be to use the Movies and Series menu, or use the search.

**Comment by Bart80-1** [comment]
> The A-Z api endpoint has been removed. There is also no A-Z listing in the Android app. The correct way forward will be to use the Movies and Series menu, or use the search.

Ok. This could be a workaround. Thanks!

**Comment by jelledp** [comment]
Version 1.3 works like a charm. Thanks!
