### ISSUE TITLE
Nothing works with latest matrix version

### ISSUE THREAD

**Issue by Rvhalewyn** [add-ons/plugin.video.vtm.go#310]
**Describe the bug**
Deinstalled both the add-on and the add-on data. Reinstalled 1.2.12+matrix.1
Get error messages from the start
Added credentials and double-checked them by relogging in through the website. Login correct in the website, still login error from the add-on. 
Programs do appear in the EPG grid (IPTV Manager), with green dots.
Try live program and VOD through the grid. 
Error log https://paste.kodi.tv/ipixoyovun 
 - Addon version:  1.2.12+matrix.1
 - Kodi version: 19.3
 - Inputstream adaptive version: 
 - Operating System: Android
 - Hardware Nvidia Pro

**Comment by michaelarnauts** [comment]
This is a known issue at the moment. See https://github.com/add-ons/plugin.video.vtm.go/issues/296

I do know a fix for this, I just need the time to implement this.
