### ISSUE TITLE
Catalog not acessible

### ISSUE THREAD

**Issue by ValentijnDemeyer** [add-ons/plugin.video.vtm.go#312]
**Describe the bug**
The catalog is not accessible anymore.

**To Reproduce**
Open the app click on A-Z or go to channel select VTM click on catalog

**Expected behavior**
Open list of all programs

**Screenshots**

**Logs**
2021-11-28 16:39:44.109 T:27256   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.vtm.go/catalog/by-channel/vtm
2021-11-28 16:39:44.140 T:26783   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vtm.go/catalog/by-channel/vtm) failed

**System**
 - Addon version: v1.2.12
 - Kodi version: 10.0.1
 - Inputstream adaptive version: 
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...): LibreElec
 - Special Hardware (RPI / Vero4K+ / ...):RPI4

**Additional context**
Seems that the catalog is removed is from the VTMGO website. Perhaps interesting to look for an alternative way to collect all programs in a list
![20211128_161518497_iOS](https://user-images.githubusercontent.com/81268821/143776707-a5077904-2a0c-4fc6-8ad0-ed156007c91f.jpg)

**Comment by michaelarnauts** [comment]
I couldn't find a workaround and have removed this in my branch that fixes up a lot of stuff.

See https://github.com/add-ons/plugin.video.vtm.go/pull/311
