### ISSUE TITLE
epg json data not correct

### ISSUE THREAD

**Issue by frankdpGH** [add-ons/plugin.video.vtm.go#314]
Hi since today having problems updating epg with iptvmanager
after epg request : 
Error Type: <class 'json.decoder.JSONDecodeError'>
Error Contents: Expecting value: line 1 column 1 (char 0)

It looks like vtm is showing a video of the masked singer when accessing the site....
https://vtm.be/the-masked-singer/the-game-is-on?redirect=/vtmgo 
see log attached (at the end)

**To Reproduce**
1. install latest version 1.3.0
2. start iptvmanager and refresh

expected is an update of epg 
**Logs**
see at the end
[kodi.log](https://github.com/add-ons/plugin.video.vtm.go/files/7748356/kodi.log)

**System**
-  Kodi (19.3 (19.3.0) Git:20211024-49a04cd6a7). Platform: Android ARM 64-bit  (also on V7)
 - Addon version: 1.3.0
 - Kodi version: 19.3
 - Inputstream adaptive version: 19.0.1
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...): Android
 - Special Hardware (RPI / Vero4K+ / ...): Android TV box or Google TV

**Comment by frankdpGH** [comment]
Looks like it was a temporary problem as of today (21/12) there is no longer a redirect on vtm.be. 
Error cannot be reproduced.  So no longer an issue, everything is working well. 
Hint on installation V1.3.0 : best is to clear authentication tokens (Expert settings) to activate the login request.

**Comment by michaelarnauts** [comment]
> Hint on installation V1.3.0 : best is to clear authentication tokens (Expert settings) to activate the login request.
Hmm, didn't the login dialog show automatically the first time after the update? That is supposed to happen...

**Comment by michaelarnauts** [comment]
I guess VTM redirected everything to the page of the masked singer. :)

https://m.gva.be/cnt/dmf20211221_92260791
