### ISSUE TITLE
Repository code can't be used in Matrix without modifications

### ISSUE THREAD

**Issue by GikikCrowchew** [add-ons/plugin.video.vtm.go#316]
**Describe the bug**

**To Reproduce**
1. download from github
2. install addon from zip (allow external sources)
3. Get error "2022-02-02 11:40:58.697 T:4564    ERROR <general>: CAddonInstallJob[plugin.video.vtm.go]: The dependency on xbmc.python version 2.26.0 could not be satisfied."

**Expected behavior**

**Screenshots**

**Logs**
Add debug logs to help troubleshoot the issue. See https://kodi.wiki/view/Log_file/Easy for more info.

**System**
 - Addon version: 1.3.0
 - Kodi version: 19.3.0
 - Inputstream adaptive version:
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...):
 - Special Hardware (RPI / Vero4K+ / ...):

**Additional context**

2022-02-02 11:40:58.697 T:4564    ERROR <general>: CAddonInstallJob[plugin.video.vtm.go]: The dependency on xbmc.python version 2.26.0 could not be satisfied.

**Comment by GikikCrowchew** [comment]
Ok, appertly I needed to download the plugin.video.vtm.go-1.3.0+matrix.1.zip version for standard windows installation and then it works. Thank you for this amazing addon!

**Comment by michaelarnauts** [comment]
You can also install the version from the repository in Kodi. You'll get automatic updates then.

**Comment by GikikCrowchew** [comment]
sadly that doesn't work (created other ticket for that one) and I tried in on 5 computers via the kodi repository. It installs an earlier version, so I think that repository is not updated

**Comment by GikikCrowchew** [comment]
euhm, ... I think you need to test things on windows, because here are the steps I took:
1. Clean install of windows (yes indeed this was a clean install of windows 10 on an intel compute stick)
2. I installed the lates version of Kodi from https://kodi.tv/download/windows
3. download the vtm go addon via the kodi video addon repository
4. Got the older version of this addon
You can test it immediately in a clean vm, I had this with 3 computers (installed a few computers for my parents tv's)

**Comment by GikikCrowchew** [comment]
I'm sory, but I don't know about Leia or anything, but I can perfectly reproduce this on any clean install.
I am happy now that I got this latest version installed manual zip install and chosing the the .matrix zip from download page.
So I am very happy :-) But it was not a simple repository install.

**Comment by GikikCrowchew** [comment]
but we are now discussing https://github.com/add-ons/plugin.video.vtm.go/issues/315
