### ISSUE TITLE
Unable to play VOD in VTM Go - "Please check error log"

### ISSUE THREAD

**Issue by Bart80-1** [add-ons/plugin.video.vtm.go#321]
**Describe the bug**
Whenever trying to play anything from "my list" (possibly other ways as well, did not check it) I get the notorious "cannot play, please check error log"-style message.

Log mentions Error Type: <type 'exceptions.UnicodeDecodeError'> ... 

**To Reproduce**
1.In "My List" start playing any item
2.See the error happening.

**Expected behavior**
The item should start playing.

**Screenshots**

**Logs**
Add debug logs to help troubleshoot the issue. See https://kodi.wiki/view/Log_file/Easy for more info.
See [log](https://paste.kodi.tv/bedonasexe)

**System**
 - Addon version: 1.3.0
 - Kodi version: 18.9.0
 - Inputstream adaptive version:2.4.8.1
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...): LibreElec 9.2.8
 - Special Hardware (RPI / Vero4K+ / ...): RPI2

**Additional context**
No problems on a RPI4 running LE 10.0.1.

**Comment by jpauwels** [comment]
This is caused by a problem in `inputstreamhelper`, which has been fixed upstream: emilsvennesson/script.module.inputstreamhelper#496. All that's left to do is wait for a release, then the dependency can be bumped. In the meantime it's easy to fix manually (see PR).

**Comment by Bart80-1** [comment]
Ok, tx. I was able to solve it by installing LibreElec 10.0.2.

**Comment by michaelarnauts** [comment]
A new version of ISH has been released today, so it might be that :)

https://github.com/emilsvennesson/script.module.inputstreamhelper/releases/tag/v0.5.9
