### ISSUE TITLE
VTMGO error

### ISSUE THREAD

**Issue by eboelens** [add-ons/plugin.video.vtm.go#323]
**Describe the bug**
After login succesfully. There is an error: VTMGO error see logfiles

**To Reproduce**
1. Open VTMGO
2. VTMGO error
3.

**Expected behavior**
Open VTMGO
**Screenshots**
no

**Logs**
https://paste.osmc.tv/hegufosapi

**System**
 - Addon version: 1.3.0
 - Kodi version: 19.4
 - Inputstream adaptive version: 19.0.3
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...): OSMC
 - Special Hardware (RPI / Vero4K+ / ...): RPI 4

**Additional context**
VRT NU   works

**Comment by michaelarnauts** [comment]
You have no profile, you should login in the Vtm Go website, and create a profile first.

**Comment by eboelens** [comment]
Thanks
