### ISSUE TITLE
Resolution in VTM GO Kodi Add-On is 720p

### ISSUE THREAD

**Issue by vermope** [add-ons/plugin.video.vtm.go#331]
Kodi 19.4 / Libreelec 10.0.2 / X86 / Arctic Horizon 2 

Hi I've noticed the streams or on-demand content are now in 720p, this used to be 1080p. The website and Android App are in 1080p.
All add-ons are up to date, max bitrate is set.
Did something change?

**Comment by vermope** [comment]
Fixed this by setting maximum bitrate to 1080p in inputstream helper settings.

**Comment by michaelarnauts** [comment]
Good to know. Thanks for updating this issue!
