### ISSUE TITLE
"Mijn Lijst/MyList" not available

### ISSUE THREAD

**Issue by vermope** [add-ons/plugin.video.vtm.go#333]
An error is received when trying to call "Mijn Lijst/MyList"

 ERROR <general>: GetDirectory - Error getting plugin://plugin.video.vtm.go/catalog/mylist

**Comment by michaelarnauts** [comment]
I'm unable to reproduce this. I can see "Mijn lijst" just fine, and all Programs seem to open fine.

Please enable debug logging in the settings, and provide a log file.

**Comment by michaelarnauts** [comment]
Also, are you sure you are running the latest version 1.3.2?

**Comment by vermope** [comment]
Yes I'm on the latest version. Ok, this is weird, the logs show indeed items in my list, at the end I get the following error:  
_ERROR <general>: [plugin.video.vtm.go] [resources.lib.modules.catalog] 404 Client Error: Not Found for url: https://lfvp-api.dpgmedia.net/vtmgo/programs/03d2c60b-c3c6-49e4-a80c-c4b5ea81cd9c/se_

https://paste-bin.xyz/84641

**Comment by vermope** [comment]
I've emptied the add-on cache. It's all good now! Why didn't I think of this sooner :) My first guess was some API related change...
