### ISSUE TITLE
404 Client Error (since october 2022)

### ISSUE THREAD

**Issue by david63236** [add-ons/plugin.video.vtm.go#334]
404 Client Error: Not Found for url:
https://lfvp-api.dpgmedia.net/vtmgo/programs/...

This problems occurs when accessing
1) Programma's - Populair on VTM GO
2) Mijn lijst

**Comment by michaelarnauts** [comment]
I'm unable to reproduce this. I can see "Mijn lijst" just fine, and all Programs seem to open fine.

Please enable debug logging in the settings, and provide a log file.

**Comment by michaelarnauts** [comment]
Also, are you sure you are running the latest version 1.3.2?

**Comment by vermope** [comment]
Clearing add-on cache resolved this for me: /storage/.kodi/userdata/addon_data/plugin.video.vtm.go/cache

**Comment by michaelarnauts** [comment]
> Clearing add-on cache resolved this for me: /storage/.kodi/userdata/addon_data/plugin.video.vtm.go/cache

There is also an option to do this from the GUI, in the Addon Settings > Expert > Clear cache (at the bottom).
