### ISSUE TITLE
screen freezez during advertizing in live mode 

### ISSUE THREAD

**Issue by cometoluc** [add-ons/plugin.video.vtm.go#340]
Al sinds de laatste vtmgo plugin-zip is er bij de filmen programmas geen reklame meer wat ik enorm tof vindt.

Alleen als men live kijkt naar een programma op vtm komt er natuurlijk reclame tussen maar in die reklameblok bevriest de stream of beeld meerdere malen, alleen bij de reklame, zoals voor het nieuws , de reklame voor het weersbericht of de voice van vlaanderen en anderen...

Is daar iets tegen te doen aub? als het beeld bevriest moet ik terug een of twee stappen naar benenden gaan en dan in kanalen terug VTM kiezen en terug erop klikken en dan gaat het enkele seconden goed of zelfs zelden zelfs gaat het op zichzelf door.

Weet u hier een manier voor om dit op te lossen aub?

Luc Van devoorde
cometoluc@telenet.be
cometoluc@gmail.com

ik werk op een windows 7.32bit pc
kodi versie 19.3(19.3.0) git:20211024-49a04cd6a7
VTMGO addon versie 1.3.2+matrix.1

**Comment by lebeno** [comment]
duplicate of #326
