### ISSUE TITLE
VTM GO authenticitation not working.

### ISSUE THREAD

**Issue by ldebt** [add-ons/plugin.video.vtm.go#341]
Version 1.3.0+matrix.1
After authenticitation "VTM GO Error" appears.
Code entered on website :
**https://login.dpgmedia.be/device/login/sso/vtm-go-androidtv?sessionId=83ecafee-7455-4df9-9c1e-6b01da9cf014&_sp_id=7e238f17-6caa-456b-ab16-e8cf0472f7c6.1669543549.1.1669544141.1669543549.e5c18b53-1260-4877-b929-619411b83681#**
via Windows 10 laptop.

**Comment by ldebt** [comment]
I have manually installed the version 1.3.2+matrix.1 =>Now the problem is solved. No further action is needed.

**Comment by kimme1024** [comment]
I seem to have the same issue on 1.3.2 now… any ideas on how to fix this?
