### ISSUE TITLE
VTMGO does not start on kodi onpc

### ISSUE THREAD

**Issue by cometoluc** [add-ons/plugin.video.vtm.go#342]
VTMGO via kodi 19.3 op windows7.32bit werkt ineens niet meer vanaf vandaag.

Hebben hier anderen ook problemen mee aub?

**Comment by pl0ng** [comment]
Can confirm: addon stopped working on kodi (linux, vero4k)
426 client error: upgrade required for url: *api.dpgmedia.net/vtmgo/..*

**Comment by kimme1024** [comment]
same here

**Comment by nagten** [comment]
Can confirm:

First got following error: 
```
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/vtmgo/tokens/refresh
```

I suspected problem with token but after refreshing token I got following error in kodi.log:
```
ERROR <general>: GetDirectory - Error getting plugin://plugin.video.vtm.go/
ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vtm.go/) failed
```

**Comment by mawn144** [comment]
Same error over here. Raspberry pi 4 - osmc

**Comment by keiem** [comment]
Same problem on Libreelec arm64.  I have it also with the Streamz addon.

The vtmgo error:

2023-01-02 17:41:31.770 T:723     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.HTTPError'>
                                                   Error Contents: 426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/vtmgo/tokens/refresh
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/addon_entry.py", line 19, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 186, in run
                                                       routing.run(params)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 22, in index
                                                       if auth.get_tokens():
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgoauth.py", line 145, in get_tokens
                                                       response = util.http_post('https://lfvp-api.dpgmedia.net/vtmgo/tokens/refresh', data={
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/util.py", line 77, in http_post
                                                       return _request('POST', url=url, params=params, form=form, data=data, token=token, profile=profile, headers=headers)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/util.py", line 184, in _request
                                                       response.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 960, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/vtmgo/tokens/refresh
                                                   -->End of Python script error report<--

and the streamz error:

2023-01-02 20:29:58.579 T:704     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.HTTPError'>
                                                   Error Contents: 426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/streamz/tokens/refresh
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.streamz/addon_entry.py", line 19, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/addon.py", line 140, in run
                                                       routing.run(params)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/addon.py", line 22, in index
                                                       tokens = auth.get_tokens()
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/streamz/auth.py", line 150, in get_tokens
                                                       response = util.http_post('https://lfvp-api.dpgmedia.net/streamz/tokens/refresh', data={
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/streamz/util.py", line 83, in http_post
                                                       return _request('POST', url=url, params=params, form=form, data=data, token=token, profile=profile, headers=headers)
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/streamz/util.py", line 183, in _request
                                                       response.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 960, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/streamz/tokens/refresh
                                                   -->End of Python script error report<--

**Comment by abanink** [comment]
Issue is obviously something changed at the remote side.

 _426 Client Error: Upgrade Required for url_ ...
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/426

The server does not accept the protocol used by the client but will respond if the client upgrades.
I haven't looked into it, but it could be that the server now wants http/2 only and the current python library "requests" doesn't support it as far as I can tell.

**Comment by keiem** [comment]
I tried to reactivate my login, but that doesn't seem to work anymore.  Everytime I activate and start the addon, it gives me a new activation code.

**Comment by abanink** [comment]
Probably this is like #131 
I already replaced the requests lib by the httpx lib to test if using http/2 solves it, but it doesn't.
So my next guess is that the headers need to be updated in the util.py library.
Currently:
_SESSION.headers = {
    'User-Agent': 'VTMGO/12.12 (be.vmma.vtm.zenderapp; build:16424; Android 24) okhttp/4.9.3',
    'x-app-version': '12',
    'x-persgroep-mobile-app': 'true',
    'x-persgroep-os': 'android',
    'x-persgroep-os-version': '24',
}_

I guess someone needs to sniff the headers from a current Android app and put them in.

**Comment by RobWouters** [comment]
These headers seem to work:
```
SESSION.headers = {
    'User-Agent': 'VTMGO/13.6 (be.vmma.vtm.zenderapp; build:16424; Android 24) okhttp/4.9.3',
    'x-app-version': '13',
    'x-persgroep-mobile-app': 'true',
    'x-persgroep-os': 'android',
    'x-persgroep-os-version': '24',
}
```

**Comment by ghen2** [comment]
With these headers I get `400 Bad request` instead of `426 Upgrade Required`.
Was this the only change you made?

**Comment by cometoluc** [comment]
is there somewhere a new vtmgo.zip file to install if this works?

**Comment by mediaminister** [comment]
See https://github.com/add-ons/plugin.video.vtm.go/pull/343
I made a test package with a working VTM GO Add-on.
Please report if something doesn't work yet.
Kodi 18 [plugin.video.vtm.go-1.3.2.zip](https://github.com/add-ons/plugin.video.vtm.go/files/10336756/plugin.video.vtm.go-1.3.2.zip)
Kodi 19 and 20: [plugin.video.vtm.go-1.3.2+matrix.1.zip](https://github.com/add-ons/plugin.video.vtm.go/files/10336757/plugin.video.vtm.go-1.3.2%2Bmatrix.1.zip)

**Comment by abanink** [comment]
works for me on Kodi 19.5

**Comment by keiem** [comment]
Should I make a separate issue for the streamz addon?  It gives the same error message.

**Comment by pckrullenbol** [comment]
Works for me (kodi 19.5 on windows) !

**Comment by pckrullenbol** [comment]
Works for me (kodi 18.x on RPi3) !

**Comment by cometoluc** [comment]
and i cannot remove anithing in my menu

**Comment by frankdpGH** [comment]
Thanks ! Working fine on Android Kodi 20 RC2 and windows 10 Kodi 19.4.

**Comment by david63236** [comment]
Windows 11 Kodi 19.3 : working fine after update of Widevine CDM

**Comment by cometoluc** [comment]
Has anyone a idee why i cannot add or remove anything in my menu please?
i tried Kodi 19 and 20: [plugin.video.vtm.go-1.3.2+matrix.1.zip to get VTMGO running again but the only issue i have is that i can not add or remove something from or to my menu

**Comment by david63236** [comment]
Windows 11 Kodi 19.3 with plugin.video.go-1.3.2+matrix1.zip : i confirm, impossible to add or remove items to My Menu.

**Comment by david63236** [comment]
Android TV Kodi 19.3 with plugin.video.go-1.3.2+matrix1.zip : not working - 404 Client Error: Not Found for url : https://lfvp-api.....

**Comment by cometoluc** [comment]
@david63236 : thanks for confirming the menu issue
nowbody reacted to my post

**Comment by peno64** [comment]
plugin.video.vtm.go-1.3.2+matrix.1.zip works on rpi4 under libreelec kodi19.4

**Comment by mediaminister** [comment]
Fixed My List:
Kodi 18: [plugin.video.vtm.go-1.3.2.zip](https://github.com/add-ons/plugin.video.vtm.go/files/10341581/plugin.video.vtm.go-1.3.2.zip)
Kodi 19 and 20 [plugin.video.vtm.go-1.3.2+matrix.1.zip](https://github.com/add-ons/plugin.video.vtm.go/files/10341582/plugin.video.vtm.go-1.3.2%2Bmatrix.1.zip)

**Comment by david63236** [comment]
> @david63236 : thanks for confirming the menu issue nowbody reacted to my post
> 
> by the way? where can i find that Widevine CDM? And what does it do? or is this only for higher windows please

Widevine CDM (re)installation can be done from the configuration screen of the "InputStream Helper" addon (program addon)

**Comment by david63236** [comment]
tested fixed "My List" plugin.video.vtm.go-1.3.2+matrix.1.zip on Windows 11 Kodi 19.3 : add and remove to My List is now possible

**Comment by david63236** [comment]
tested fixed "My List" plugin.video.vtm.go-1.3.2+matrix.1.zip on Android TV Kodi 19.3
1) add to My List is possible
2) items already added to My List still offer the possibility to add to My List (should have the possibility to remove from My List)
3) access to My List is still impossible : 404 Client Error: Not Found for url: https://lfvp-api.dpgmedia.net/VTM_GO/detail/6ba6d1aa-daca- (delete from My List
4) the 404 Client Error occurs on some other items to, for instance "Aanbevelingen - Internationale comedy" gives the error, but "Aanbevelingen - Vlaamse comedy" works

**Comment by david63236** [comment]
UPDATE: I noticed that the Aanbevelingen menu was different (longer) on Android TV than on Windows,
so I did a cache clean for the vtm.go addon on Android TV and the 404 Client Error seems to be solved.

**Comment by michaelarnauts** [comment]
I've merged https://github.com/add-ons/plugin.video.vtm.go/pull/343 and will do a release soon.

Thanks @mediaminister for the fix, and all others for testing!
