### ISSUE TITLE
Error since yesterday

### ISSUE THREAD

**Issue by benbelgium** [add-ons/plugin.video.vtm.go#345]
VTM Go was working fine until yesterday. Suddenly I want launch it and it gives me "VTM Go error, check the log for more information"
I went into the add-on's settings, chose clear cache, tried again. It asked me to go to the VTM page from another device to authenticate, did exactly that and gives me the same error.
I removed the add-on completely, and reinstalled it, again same situation.
By the way; if I exit VTM Go to the main KODI menu, and want to enter the VTM Go add-on again, it will always ask me again to go to the VTM page and enter the code (maybe that gives a clue)

From my windows PC I went onto my CoreELEC KODI media player and checked all log files I could find, but nothing became clear.
Where are other log files located?

1. Launch kodi
2. Open VTM Go

 - Addon version: 1.3.2matrix+
 - Kodi version: matrix 19.5
 - Inputstream adaptive version: 19.0.7.1
 - Operating System: CoreElec
 - Special Hardware (RPI / Vero4K+ / ...): Minix Neo T5

Many Thanks!

Ben

**Comment by peno64** [comment]
Most probably the same as https://github.com/add-ons/plugin.video.vtm.go/issues/342
An update is underway or manually install https://github.com/add-ons/plugin.video.vtm.go/releases/tag/v1.3.3

**Comment by marnux** [comment]
Any idea what the elapsed time is between the new version being build and it being available on the official kodi repo? Will install manually for now, but it would be nice to know when it can be updated automagically.

**Comment by benbelgium** [comment]
Hi all

I can confirm the new version 1.3.3matrix+ doesn't have a problem anymore

Notice1: when i wrote this issue 2 days ago I was still on my Minix Neo T5 with CoreElec Kodi Matrix 19.5
I tried upgrading the VTM Go app by simply choosing the zip file from a USB stick, it upgraded but the problem still existed...
Afterwards I removed it completely including all settings, did a fresh install from the stick and the problem still existed...
I gave up thinking that apparently the new 1.3.3 version wasn't the solution after all...
Yesterday my new TV arrived which has Android TV built in. There I just installed Kodi from the App Store, and noticed it was version 19.3 but didn't care.. I first installed the 1.3.2 version from the repository to notice it was still broken (but I was lazy lying in my sofa so I tried it anyway :)). Afterwards I completely removed it and installed the new 1.3.3 from the stick, and it was working fine. Was it because it was kodi 19.3 and not 19.5? Was it because it was Kodi on Android and not the CoreElec version? I don't know, but it appears something was different.

Notice2: When I was installing VTM Go, Go Play and VRT Max on my old minix/coreelec system, I don't know which one of the 3 did it, but one did a very weird inputstream adaptive install... it said something like I had to get the ISO from google which was 1.2Gb first to extract it from that, and when I hit continue it took a long time downloading, extracting, installing. Could this have broken everything? When I installed exactly the same 3 add-ons yesterday this never happened? Did I install it in a different order? maybe.... (so possibly for example it was VRT Max which did this weird ISO install, but because I now installed VTM Go first the inputstream adaptive was already installed and it was no longer necessary to do this weird thing? I dunno). Was it maybe different on matrix 19.5? Again, I can't tell...

Just writing my thoughts in case this might help somebody
For me this issue can get closed, I'm happy
Many thanks
Cheers

Ben

**Comment by michaelarnauts** [comment]
Sometimes, Kodi caches an old addon, even though you just updated it. I suggest to always restart Kodi when you have updated an Add-on. It might be that 1.3.2 was still in memory.

The inputstream adaptive thing you saw is normal. The first time on an ARM device, it needs to download a quite large ISO file from the google servers to extract the widevine library from it.

**Comment by peno64** [comment]
A small note about widevine. This is not only the first time, but also when there is an update of widevine and indeed both are normal.
