### ISSUE TITLE
Items displayed in episode list for which there are no streams.

### ISSUE THREAD

**Issue by Bart80-1** [add-ons/plugin.video.vtm.go#348]
**Describe the bug**
Items displayed in episode list for which there are no streams.

**To Reproduce**
1. Navigate to "Sturm der Liebe"
2. Choose episode 145
3. Error is displayed; logs suggest there is no stream

**Expected behavior**
Episode 145 plays

**Screenshots**
None

**Logs**
Add debug logs to help troubleshoot the issue. See https://kodi.wiki/view/Log_file/Easy for more info.
[](https://paste.kodi.tv/irodizomim)

**System**
 - Addon version:1.3.3+matrix.1
 - Kodi version: 19.4 (19.4.0)
 - Inputstream adaptive version:19.0.7.1
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...): LibreElec
 - Special Hardware (RPI / Vero4K+ / ...): RPI

**Comment by david63236** [comment]
Same problem for Kodi 19.3 on Windows and Android TV (with add-on version 1.3.3+matrix.1).
All episodes after "Sturm der Liebe 18x140" don't play.
error: No stream found that we can handle

**Comment by mediaminister** [comment]
I fixed it. Please test:
Kodi 19/20: [plugin.video.vtm.go-1.3.3+matrix.1.zip](https://github.com/add-ons/plugin.video.vtm.go/files/10536071/plugin.video.vtm.go-1.3.3%2Bmatrix.1.zip)
Kodi 18: [plugin.video.vtm.go-1.3.3.zip](https://github.com/add-ons/plugin.video.vtm.go/files/10536070/plugin.video.vtm.go-1.3.3.zip)

**Comment by mediaminister** [comment]
Please test if every video plays fine:
Kodi 19/20: [plugin.video.vtm.go-1.3.3+matrix.1.zip](https://github.com/add-ons/plugin.video.vtm.go/files/10544250/plugin.video.vtm.go-1.3.3%2Bmatrix.1.zip)
Kodi 18: [plugin.video.vtm.go-1.3.3.zip](https://github.com/add-ons/plugin.video.vtm.go/files/10544249/plugin.video.vtm.go-1.3.3.zip)

**Comment by Bart80-1** [comment]
Tested the Matrix plugin for both the Sturm der Liebe and Expeditie Gooris in Amerika episodes => both work nicely.
Big thanks!

**Comment by david63236** [comment]
Tested yesterday's version of Kodi 19.3 add-on on Windows and Android TV,
Sturm der Liebe, Expeditie Gooris in Amerika and Allo Allo play completly without freezing and with good subtitles.
Thanks @mediaminister for the fix.

**Comment by david63236** [comment]
@benbelgium are you using the latest test version of the add-on?
You have to install the add-on download from last @mediaminister message for this issue.
If yes, what version of Kodi and operating system are you using?

**Comment by david63236** [comment]
@benbelgium Yes, same name but different version.

**Comment by david63236** [comment]
For the previous tests,  I always manually stopped the video just before the end.
But when I let the video play until the very end, the VTM add-on crashes, and a restart of Kodi is needed to repair the VTM add-on.
This occurs with Kodi 19.3 on Android TV.
Sorry, the logfile has been erased by the restart.

I found an other problem with the last version on Android TV (Kodi 19.3).
When playing a video from start to the very end, the VTM add-on crashes

-- Kodi 19.3 on Android TV (still trying to retrieve the logfile on Android TV)

**Comment by michaelarnauts** [comment]
Fixed in https://github.com/add-ons/plugin.video.vtm.go/pull/349
