### ISSUE TITLE
Episodes Missing

### ISSUE THREAD

**Issue by M0nty99** [add-ons/plugin.video.vtm.go#362]
**Describe the bug**
Boer zkt vrouw Season 6 only showing Oproepaflevering 3, while there are 3 episodes on VTM GO

**To Reproduce**
1. Log in and load season
2. Checked VTM GO website
3.

**Expected behavior**
All episodes showing from the Season

**System**
 - Addon version: Latest Version
 - Kodi version: 19.5
 - Inputstream adaptive version:
 - Operating System: LibreElec 10.0.4
 - Special Hardware (RPI / Vero4K+ / ...): Raspberry PI 4

**Additional context**

**Comment by michaelarnauts** [comment]
I've found the issue, all three episodes have the same index (you can see the 0. on the VTM GO website as well), and the Addon assumed those would be unique.

Can you try with this zip? https://github.com/add-ons/plugin.video.vtm.go/pull/363#issuecomment-1646872140

**Comment by M0nty99** [comment]
Hi @michaelarnauts 

That did the trick! Thank you very much for the fast resolution, you made my wife happy ;-) 
Happy wife = happy life so am I happy too :-D


Thanks!
