### ISSUE TITLE
Issue #342 pop ups again.  Need to bump x-app-version to 14 in util.py to make it work again (same with streamz)

### ISSUE THREAD

**Issue by molano999** [add-ons/plugin.video.vtm.go#366]
**Describe the bug**
See title

**To Reproduce**
1.
2.
3.

**Expected behavior**

**Screenshots**

**Logs**
Add debug logs to help troubleshoot the issue. See https://kodi.wiki/view/Log_file/Easy for more info.

**System**
 - Addon version:
 - Kodi version:
 - Inputstream adaptive version:
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...):
 - Special Hardware (RPI / Vero4K+ / ...):

**Additional context**

**Comment by peno64** [comment]
I can confirm this. kodi.log has following errors:

2023-11-02 23:23:08.027 T:31017   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.HTTPError'>
                                                   Error Contents: 426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/VTM_GO/tokens/refresh
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/addon_entry.py", line 19, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 186, in run
                                                       routing.run(params)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 22, in index
                                                       if auth.get_tokens():
                                                          ^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgoauth.py", line 145, in get_tokens
                                                       response = util.http_post('https://lfvp-api.dpgmedia.net/VTM_GO/tokens/refresh', data={
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/util.py", line 77, in http_post
                                                       return _request('POST', url=url, params=params, form=form, data=data, token=token, profile=profile, headers=headers)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/util.py", line 184, in _request
                                                       response.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/VTM_GO/tokens/refresh
                                                   -->End of Python script error report<--

**Comment by davidvf** [comment]
Correct, i am hitting the samen problem.
Updating the `x app version` to 14 solved it.
`.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/util.py`

**Comment by michaelarnauts** [comment]
This is fixed in https://github.com/add-ons/plugin.video.vtm.go/releases/tag/v1.4.3

Can you try this release?

**Comment by peno64** [comment]
Seems to work fine here with this update. Both live and delayed vieuw.
This on a RP4 with libreelec.

Thx

**Comment by thomasddn** [comment]
Just wondering: how long does it take before this new version pops up in the default Kodi repository? It doesn't show any update on my installation (OSMC), or am I missing something?

**Comment by esjay90** [comment]
I was also waiting, but updated it manually by downloading the zip from Github

**Comment by davidbe** [comment]
I just saw that the recent releases are only for matrix. The latest non-matrix was version 1.4.1 - which I have.
@thomasddn if you are tech-savvy enough, you can edit yourself. This change is not that huge: https://github.com/add-ons/plugin.video.vtm.go/pull/369/files

Are non-matrix releases will be available?

**Comment by thomasddn** [comment]
Thanks for the blazingly fast responses @esjay90 and @davidbe! I'm on Kodi v20.2 and the installed VTM GO version is 1.4.2+matrix.1. Based on that I would assume v1.4.3 should also become available.

I prefer not to install it manually, because then I'll need to check for updates myself on a regular basis. With auto-update I have something less to worry about. ;)

**Comment by michaelarnauts** [comment]
> I just saw that the recent releases are only for matrix. The latest non-matrix was version 1.4.1 - which I have. @thomasddn if you are tech-savvy enough, you can edit yourself. This change is not that huge: https://github.com/add-ons/plugin.video.vtm.go/pull/369/files
> 
> Are non-matrix releases will be available?

Releases prior to matrix (Leia) aren't supported anymore, but you could modify the addon.xml manually if you want. They will probably still work, bit you should really consider to upgrade your Kodi version.

**Comment by michaelarnauts** [comment]
> Just wondering: how long does it take before this new version pops up in the default Kodi repository? It doesn't show any update on my installation (OSMC), or am I missing something?

Usually, this happens in a day, but it seems that haven't merged the new release yet.

You can follow up new submission for the Kodi repository here: https://github.com/xbmc/repo-plugins/pulls

**Comment by davidbe** [comment]
> > I just saw that the recent releases are only for matrix. The latest non-matrix was version 1.4.1 - which I have. @thomasddn if you are tech-savvy enough, you can edit yourself. This change is not that huge: https://github.com/add-ons/plugin.video.vtm.go/pull/369/files
> > Are non-matrix releases will be available?
> 
> Releases prior to matrix (Leia) aren't supported anymore, but you could modify the addon.xml manually if you want. They will probably still work, bit you should really consider to upgrade your Kodi version.

I really would like that, but I'm running Kodi on an old device (Odroid C2) and I only found coreelec to supply an out of the box experience on legacy. But maybe I should try out dietpi...
