### ISSUE TITLE
Wiki-pages up-to-date?

### ISSUE THREAD

**Issue by davidbe** [add-ons/plugin.video.vtm.go#372]
**Describe the bug**
Are the wiki-pages (https://github.com/add-ons/plugin.video.vtm.go/wiki/Authentication-API) up to date?

**To Reproduce**

Perform Redirect Request 1:
``` bash
curl  -X GET \
 -H 'Cookie: authId=2dc44dfb-514f-48cb-9962-71836534ee41' \
'https://login2.vtm.be/authorize?response_type=code&response_mode=form_post&client_id=vtm-go-web&scope=openid%20profile&state=nQhCIMGeFoK6oyNZ-G8S8tA47r8Yt3EsqanKbBl4FgY=&redirect_uri=https://vtm.be/vtmgo/login-callback'
```

Response contains html with error that login with user & password aren't supported anymore.

**Expected behavior**
A positive response.

--> I guess that the wiki-page is outdated. Can  you point out where authentication is started in the code?

**Comment by michaelarnauts** [comment]
The wiki page isn't up to date. Only device login is supported now. See https://github.com/add-ons/plugin.video.vtm.go/blob/master/resources/lib/vtmgo/vtmgoauth.py for the code
