### ISSUE TITLE
VTMGo Plug-in won't start anymore

### ISSUE THREAD

**Issue by PeterCloet** [add-ons/plugin.video.vtm.go#390]
**Describe the bug**
VTMGo add-on will not start. See log for details.

**To Reproduce**
1. Start VTMGo add-on

**Logs**
https://paste.kodi.tv/xizawimeve.kodi

**System**
 - Addon version: 1.4.4
 - Kodi version: 20.3
 - Inputstream adaptive version: v20.3.18.1
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...): LibreElec 11.0.6
 - Special Hardware (RPI / Vero4K+ / ...): RPI

**Comment by davidbe** [comment]
This is a known issue for version 1.4.4. VTMGo's back-end has changed.
For now, you can update manually. Follow the instructions on this post: https://github.com/add-ons/plugin.video.vtm.go/issues/387#issuecomment-2226821209

**Comment by PeterCloet** [comment]
That solved the problem. Thanks for pointing this out to me!
