### ISSUE TITLE
GOPLAY is not working.

### ISSUE THREAD

**Issue by ldebt** [add-ons/plugin.video.vtm.go#395]
GOPLAY can not open any tv program.

Open KODI >> open the GOPLAY addon >> select channel >> select date >> try to open date, won't work >> "Fault in GOPLAY more info in log file"

    Google Chromecast HD
    Addon version: 0.4.11+matrix.1
    Kodi version: V. 21.1
    Operating System: Android

**Comment by davidbe** [comment]
Wrong github-repo. This repo is for vtm go add-on. Goplay is https://github.com/add-ons/plugin.video.goplay
If I remember correctly, I had to install de add-on by hand via .zip-file.
