### ISSUE TITLE
API-17 The Masked Singer gives Error when opening "Season 4" folder

### ISSUE THREAD

**Issue by trick72** [add-ons/plugin.video.vtm.go#396]
**Describe the bug**
I am on latest API-17 branch of this plugin. Most recent programs play fine (De Verraders etc.)
The Masked Singer however gives an error message when opening the "Season 4" folder. So I don't even see the episode and thus I cannot play the program. It does work on my PC, web-based via the VTM go website.
"Behind the mask" does work fine! Does anyone else experience this issue?

**To Reproduce**
1. browse VTM go
2. Open The Masked Singer, you see all 4 seasons listed
3. Open Season 4, an error is shown 'check log for details'

**Expected behavior**

**Screenshots**

**Logs**
Add debug logs to help troubleshoot the issue. See https://kodi.wiki/view/Log_file/Easy for more info.

**System**
 - Addon version:-17
 - Kodi version:12.0.1
 - Inputstream adaptive version:latest
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...):LibreElec
 - Special Hardware (RPI / Vero4K+ / ...):RPI 5

**Additional context**

**Comment by vctoon** [comment]
same here but:
-on a RPI 4
-for season 4 of 'De Code van Coppens'

**Comment by davidbe** [comment]
I tried it  yesterday evening and had no issues. Did you clear the cache?

**Comment by trick72** [comment]
Oh never tried that. Yes, clearing the cache fixed it for me. Thanks!
